spring.datasource.username = root
spring.datasource.password = Training!12345
spring.datasource.url = jdbc:mysql://localhost:3306/welness-app?serverTimezone=UTC

spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL8Dialect
server.port=8081
spring.jpa.show-sql = true

spring.jpa.hibernate.ddl-auto = update
